# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insertData.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, uic
from DataKendaraan import *
from Sqlitehelper import *
import sqlite3


class Ui_InsertData(object):

    def loadData(self):
        dlg = uic.loadUi("database.ui")
        while (dlg.tableWidget.rowCount() > 0):
            dlg.tableWidget.removeRow(0)
        dlg = uic.loadUi("database.ui")
        helper = SqliteHelper("Kendaraan.db")
        dataKendaraan = helper.select("Select * FROM datakendaraan")
        for row_number, user in enumerate(dataKendaraan):
            dlg.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(user):
                cell = QtWidgets.QTableWidgetItem(str(data))
                dlg.tableWidget.setItem(row_number, column_number, cell)


    def clearData(self):
        dlg = uic.loadUi("database.ui")
        while (dlg.tableWidget.rowCount() > 0):
            dlg.tableWidget.removeRow(0)

    def addData(self):
        helper = SqliteHelper("Kendaraan.db")
        Id = self.idLine.text()
        Name = self.namaLine.text()
        noPlate = self.nomorpolisiLine.text()
        Vehicle = self.kendaraanLine.text()
        Type = self.jenisLine.text()
        Year = self.tahunLine.text()
        City = self.kotaLine.text()
        Status = self.statusLine.text()

        data = (Id, Name, noPlate, Vehicle, Type, Year, City, Status)
        helper.insert("INSERT INTO datakendaraan (ID,NAMA,NO_POLISI,KENDARAAN,JENIS,TAHUN,KOTA,STATUS) VALUES(?,?,?,?,?,?,?,?)", data)
        self.clearData()
        self.loadData()
        self.clear()
        self.showMessageBox("Success !!", "Data Sukses dimasukkan !")

    def clear(self):
        self.idLine.setText("")
        self.namaLine.setText("")
        self.nomorpolisiLine.setText("")
        self.kendaraanLine.setText("")
        self.jenisLine.setText("")
        self.tahunLine.setText("")
        self.kotaLine.setText("")
        self.statusLine.setText("")

    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 383)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(444, 383))
        MainWindow.setMaximumSize(QtCore.QSize(444, 383))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 11, 381, 327))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.idLine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLine.setFont(font)
        self.idLine.setObjectName("idLine")
        self.horizontalLayout.addWidget(self.idLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.namaLine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.namaLine.setFont(font)
        self.namaLine.setObjectName("namaLine")
        self.horizontalLayout_2.addWidget(self.namaLine)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.nomorpolisiLine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nomorpolisiLine.setFont(font)
        self.nomorpolisiLine.setObjectName("nomorpolisiLine")
        self.horizontalLayout_3.addWidget(self.nomorpolisiLine)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.kendaraanLine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kendaraanLine.setFont(font)
        self.kendaraanLine.setObjectName("kendaraanLine")
        self.horizontalLayout_4.addWidget(self.kendaraanLine)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.jenisLine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.jenisLine.setFont(font)
        self.jenisLine.setObjectName("jenisLine")
        self.horizontalLayout_5.addWidget(self.jenisLine)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.tahunLine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tahunLine.setFont(font)
        self.tahunLine.setObjectName("tahunLine")
        self.horizontalLayout_6.addWidget(self.tahunLine)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.kotaLine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kotaLine.setFont(font)
        self.kotaLine.setObjectName("kotaLine")
        self.horizontalLayout_9.addWidget(self.kotaLine)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.statusLine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusLine.setFont(font)
        self.statusLine.setObjectName("statusLine")
        self.horizontalLayout_7.addWidget(self.statusLine)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.clearButton = QtWidgets.QPushButton(self.layoutWidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_8.addWidget(self.clearButton)
        self.addButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_8.addWidget(self.addButton)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 444, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)



        self.clearButton.clicked.connect(self.clear)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Insert Data"))
        self.label_8.setText(_translate("MainWindow", "Insert Data"))
        self.label.setText(_translate("MainWindow", "Id"))
        self.label_2.setText(_translate("MainWindow", "Nama Pemilik"))
        self.label_3.setText(_translate("MainWindow", "Nomor Polisi"))
        self.label_4.setText(_translate("MainWindow", "Kendaraan"))
        self.label_5.setText(_translate("MainWindow", "Jenis"))
        self.label_6.setText(_translate("MainWindow", "Tahun"))
        self.label_10.setText(_translate("MainWindow", "Kota"))
        self.label_7.setText(_translate("MainWindow", "Status"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.label_9.setText(_translate("MainWindow", "Data Kendaraan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_InsertData()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

